### ISSUE TITLE
Hook not triggered for internal method

### ISSUE THREAD

**Issue by Ph0tonic** [CodeIntelligenceTesting/jazzer#237]
Hello,

I have a problem with hooks that do not seem to trigger.
Here is a simple reproducer, where I just set up a hook for method `java.util.PriorityQueue.siftUpUsingComparator(PriorityQueue.java:675)` and where I throw an Exception in case the hook is not triggered.
When executing it, I get the following output where we can see that I can trigger this function without triggering the hook.
Thank you in advance for any help.

\cc @prashast

**Note :** hooking the `add` method is working but hooking internal methods that are called behind the scene is not.

For `Build.bazel` :
```bazel
java_fuzz_target_test(
    name = "ReproducerHookFuzzer",
    srcs = [
        "src/main/java/com/example/ReproducerHookFuzzer.java",
        "src/main/java/com/example/ReproducerHook.java",
    ],
    # Comment out the next line to keep the fuzzer running indefinitely.
    hook_classes = ["com.example.ReproducerHook"],
    target_class = "com.example.ReproducerHookFuzzer",
)
```

My hook `reproducerHook.java`
```java
package com.example;
import java.io.*; 

import java.util.PriorityQueue;
import com.code_intelligence.jazzer.api.HookType;
import com.code_intelligence.jazzer.api.MethodHook;
import java.lang.invoke.MethodHandle;
import com.code_intelligence.jazzer.api.Jazzer;
import com.code_intelligence.jazzer.api.FuzzerSecurityIssueHigh;

public class ReproducerHook {
  @MethodHook(type = HookType.BEFORE, targetClassName = "java.util.PriorityQueue",
      targetMethod = "siftUpUsingComparator", targetMethodDescriptor = "")
  public static void
  hookRuntime(MethodHandle handle, Object thisObject, Object[] args, int hookId) {
    Jazzer.reportFindingFromHook(new FuzzerSecurityIssueHigh("getOutputProperties TODO Check triggered !"));
    throw new FuzzerSecurityIssueHigh("TemplatesImpl.getOutputProperties has been called");
  }
}
```

And finally my dummy fuzzer `ReproducerHookFuzzer.java`:
```java
package com.example;

import java.io.*; 

import java.util.Comparator;
import java.util.PriorityQueue;
import java.lang.AssertionError;

public class ReproducerHookFuzzer {
  public static void fuzzerTestOneInput(byte[] input) throws IOException, ClassNotFoundException {
    final Comparator<Object> comparator = new Comparator<Object>() {
      public int compare(Object i1, Object i2) {
        throw new AssertionError();
      }
    };
    
    final PriorityQueue<Object> queue = new PriorityQueue<Object>(2, comparator);
		queue.add(new Integer("1"));
		queue.add(new Integer("2"));
  }
}
```

That outputs the following, where we can see that the hook is not triggered despite the method having been called :
```sh
root@2418a07cb720:/tmp/jazzer/examples# ../bazelisk-linux-amd64 run //examples:ReproducerHookFuzzer
INFO: Analyzed target //examples:ReproducerHookFuzzer (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //examples:ReproducerHookFuzzer up-to-date:
  bazel-bin/examples/ReproducerHookFuzzer.jar
  bazel-bin/examples/ReproducerHookFuzzer
INFO: Elapsed time: 0.172s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: external/bazel_tools/tools/test/test-setup.sh examples/ReproducerHookFuzzer jazzer/driver/jazzer_driver jazzer/examples/ReproducerHookFuzzINFO: Build completed successfully, 1 total action
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //examples:ReproducerHookFuzzer
-----------------------------------------------------------------------------
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
INFO: Loaded 1 hooks from com.example.ReproducerHook
INFO: Loaded 8 hooks from com.code_intelligence.jazzer.sanitizers.Deserialization
INFO: Loaded 1 hooks from com.code_intelligence.jazzer.sanitizers.ReflectiveCall
INFO: Loaded 3 hooks from com.code_intelligence.jazzer.sanitizers.ExpressionLanguageInjection
INFO: Loaded 8649 no-throw method signatures
INFO: Instrumented com.example.ReproducerHookFuzzer (took 95 ms, size +34%)
INFO: libFuzzer ignores flags that start with '--'
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2735196724
INFO: Loaded 1 modules   (512 inline 8-bit counters): 512 [0x7f28e84bc010, 0x7f28e84bc210), 
INFO: Loaded 1 PC tables (512 PCs): 512 [0x7f28bafff010,0x7f28bb001010), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: Instrumented com.example.ReproducerHookFuzzer$1 (took 2 ms, size +30%)

== Java Exception: java.lang.AssertionError
        at com.example.ReproducerHookFuzzer$1.compare(ReproducerHookFuzzer.java:13)
        at java.base/java.util.PriorityQueue.siftUpUsingComparator(PriorityQueue.java:675)
        at java.base/java.util.PriorityQueue.siftUp(PriorityQueue.java:652)
        at java.base/java.util.PriorityQueue.offer(PriorityQueue.java:345)
        at java.base/java.util.PriorityQueue.add(PriorityQueue.java:326)
        at com.example.ReproducerHookFuzzer.fuzzerTestOneInput(ReproducerHookFuzzer.java:19)
DEDUP_TOKEN: 5fd26f5695a87482
== libFuzzer crashing input ==
MS: 0 ; base unit: 0000000000000000000000000000000000000000


artifact_prefix='/root/.cache/bazel/_bazel_root/7b91779107cdc414b1652b7e849f6e9a/execroot/jazzer/bazel-out/k8-opt/testlogs/examples/ReproducerHookFuzzer/test.outputs/'; Test unit written to /root/.cache/bazel/_bazel_root/7b91779107cdc414b1652b7e849f6e9a/execroot/jazzer/bazel-out/k8-opt/testlogs/examples/ReproducerHookFuzzer/test.outputs/crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64: 
reproducer_path='/root/.cache/bazel/_bazel_root/7b91779107cdc414b1652b7e849f6e9a/execroot/jazzer/bazel-out/k8-opt/testlogs/examples/ReproducerHookFuzzer/test.outputs'; Java reproducer written to /root/.cache/bazel/_bazel_root/7b91779107cdc414b1652b7e849f6e9a/execroot/jazzer/bazel-out/k8-opt/testlogs/examples/ReproducerHookFuzzer/test.outputs/Crash_da39a3ee5e6b4b0d3255bfef95601890afd80709.java
```

**Comment by fmeum** [comment]
Jazzer hooks apply to method *callsites*, not the methods themselves. Thus, for a hook to be called, the callsite has to be instrumented by Jazzer. By default, Jazzer does not instrument the Java standard library, so it never sees the call of `PriorityQueue.siftUpUsingComparator` in `java.util.PriorityQueue.siftUp`.

You can control the exact set of classes instrumented by Jazzer using the `--instrumentation_includes` (enables all types of instrumentation) and `--custom_hook_includes` (enables only hooks on callsites, but not e.g. coverage instrumentation) arguments. If you want `java.lang.PriorityQueue` as well as your fuzz target to be instrumented, you could try to add
```
--instrumentation_includes=java.lang.PriorityQueue:com.example.**
```
or
```
--custom_hook_includes=java.lang.PriorityQueue
```
depending on whether you also want coverage instrumentation for `java.lang.PriorityQueue` or not.

**Comment by Ph0tonic** [comment]
Thank you very much ! These solutions work perfectly and I should be able to use them in my project.
