### ISSUE TITLE
How to fuzz java program when the jdk argument '--enable-preview' enabled

### ISSUE THREAD

**Issue by FourierX9** [CodeIntelligenceTesting/jazzer#241]
Hi: I am using Jazzer to fuzzing with JDK17 new preview feature. And I got a Error goes like this:

== Java Exception: java.lang.UnsupportedClassVersionError: Preview features are not enabled for Error (class file version 61.65535). Try running with '--enable-preview'
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at Main.fuzzerTestOneInput(Main.java:11)

I guess this is not the problem with the code being tested. But the jdk argument '--enable-preview' is not contained when running the code. I have checked with the document and the help of jazzer but I did not find any related information. Would you help me with it? 

Thanks

**Comment by fmeum** [comment]
You can pass arguments to the JVM via `--jvm_args`, which isn't mentioned in the README yet. Could you check whether https://github.com/CodeIntelligenceTesting/jazzer/blob/823e8d1a7382381697479d1e86a7911833fdc215/README.md#passing-jvm-arguments helps you resolve this issue?

**Comment by FourierX9** [comment]
It works!!! Sorry for my stupid question. Thank you so much
