### ISSUE TITLE
ClassVisitor throws IllegalArgumentException: Unsupported api

### ISSUE THREAD

**Issue by schirrmacher** [CodeIntelligenceTesting/jazzer#55]
I try to apply Jazzer for a Spring Boot project which has many dependencies. I created a fat Jar file with the ShadowJar plugin so that every dependency can be accessed by Jazzer when executing `./jazzer`. Besides, dependencies and my fuzz tests are written in Kotlin (1.4.31), for building I'm using Gradle (6.8.3).

Unfortunatley exceptions are thrown for every instrumented class, like:

```
#8 1.035 java.lang.IllegalArgumentException: Unsupported api 589824
#8 1.035 WARN: Failed to instrument com.fasterxml.jackson.databind.introspect.ConcreteBeanPropertyBase, skipping
#8 1.035 	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:70)
#8 1.035 	at com.code_intelligence.jazzer.instrumentor.HookInstrumentor$instrument$interceptor$1.<init>(HookInstrumentor.kt:30)
#8 1.035 	at com.code_intelligence.jazzer.instrumentor.HookInstrumentor.instrument(HookInstrumentor.kt:30)
#8 1.035 	at com.code_intelligence.jazzer.instrumentor.ClassInstrumentor.hooks(ClassInstrumentor.kt:40)
#8 1.035 	at com.code_intelligence.jazzer.agent.RuntimeInstrumentor.instrument(RuntimeInstrumentor.kt:139)
#8 1.035 	at com.code_intelligence.jazzer.agent.RuntimeInstrumentor.transform(RuntimeInstrumentor.kt:110)
#8 1.035 	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
#8 1.035 	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
#8 1.035 	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
#8 1.035 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
#8 1.035 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
#8 1.035 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
#8 1.035 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
#8 1.035 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
#8 1.035 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
#8 1.035 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
#8 1.035 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
#8 1.035 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
#8 1.035 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
#8 1.035 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
#8 1.035 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
#8 1.035 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
#8 1.035 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
#8 1.035 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
#8 1.035 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
#8 1.035 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
#8 1.035 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
#8 1.035 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
#8 1.035 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
#8 1.035 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
#8 1.035 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
#8 1.035 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
#8 1.035 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
#8 1.035 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
#8 1.035 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
#8 1.035 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
#8 1.035 	at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:351)
#8 1.035 	at net.grandcentrix.cellulariot.cellularhub.devicemanagement.device.domain.vodafone.VodafoneMessageParser.<init>(VodafoneMessageParser.kt:11)
#8 1.035 	at net.grandcentrix.cellulariot.cellularhub.devicemanagement.device.domain.vodafone.VodafoneEventMessageParser.<init>(VodafoneEventMessageParser.
```

I assume that the `ClassVisitor` expects a different class file format version. Is that an issue which might be related to my compiling process or may it be a Jazzer problem?

**Comment by schirrmacher** [comment]
Ok, there was an issue with duplicate asm versions used by dependencies.

I solved it by shadowing:
```
tasks.withType<ShadowJar> {
    enabled = true
    archiveFileName.set("chub-dependencies.jar")
    // use Zip64
    // otherwise an error is thrown: "archive contains more than 65535 entries"
    isZip64 = true
    relocate("org.objectweb.asm", "shadow.org.objectweb.asm")
}
```

**Comment by fmeum** [comment]
Thanks for the bug report. It should not be on the user to apply shading here, so I have drafted PR #56 that would shade the dependencies on our side. Could you try whether this is fixed with the `jazzer_agent_deploy.jar` built with that PR via the command:
```
./bazelisk-linux-amd64 build //agent:jazzer_agent_deploy.jar
```
