### ISSUE TITLE
java.lang.IllegalArgumentException: argument type mismatch

### ISSUE THREAD

**Issue by freedom1b2830** [CodeIntelligenceTesting/jazzer#602]
```java
Jazzer.main(new String[] {

				"--autofuzz=ru.vyarus.java.generics.resolver.GenericsResolver::resolve",

				"--keep_going=2000",

				"-detect_leaks=1"

		});
```
```xml
		<dependency>
			<groupId>ru.vyarus</groupId>
			<artifactId>generics-resolver</artifactId>
			<version>3.0.1</version>
		</dependency>
```
```
INFO: Loaded 1802 hooks from com.code_intelligence.jazzer.runtime.TraceCmpHooks
INFO: Loaded 4 hooks from com.code_intelligence.jazzer.runtime.TraceDivHooks
INFO: Loaded 2 hooks from com.code_intelligence.jazzer.runtime.TraceIndirHooks
INFO: Loaded 4 hooks from com.code_intelligence.jazzer.runtime.NativeLibHooks
INFO: Loaded 5 hooks from com.code_intelligence.jazzer.sanitizers.Deserialization
INFO: Loaded 5 hooks from com.code_intelligence.jazzer.sanitizers.ExpressionLanguageInjection
INFO: Loaded 70 hooks from com.code_intelligence.jazzer.sanitizers.LdapInjection
INFO: Loaded 46 hooks from com.code_intelligence.jazzer.sanitizers.NamingContextLookup
INFO: Loaded 1 hooks from com.code_intelligence.jazzer.sanitizers.OsCommandInjection
INFO: Loaded 76 hooks from com.code_intelligence.jazzer.sanitizers.ReflectiveCall
INFO: Loaded 8 hooks from com.code_intelligence.jazzer.sanitizers.RegexInjection
INFO: Loaded 16 hooks from com.code_intelligence.jazzer.sanitizers.RegexRoadblocks
INFO: Loaded 19 hooks from com.code_intelligence.jazzer.sanitizers.SqlInjection
INFO: Instrumented test.Fuzzer (took 514 ms, size +16%)
INFO: Instrumented ru.vyarus.java.generics.resolver.GenericsResolver (took 149 ms, size +8%)
INFO: Instrumented ru.vyarus.java.generics.resolver.context.GenericsContext (took 309 ms, size +7%)
INFO: Instrumented ru.vyarus.java.generics.resolver.context.AbstractGenericsContext (took 246 ms, size +9%)
INFO: libFuzzer ignores flags that start with '--'
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3335829751
INFO: Loaded 1 modules   (512 inline 8-bit counters): 512 [0x7fa3a48e5680, 0x7fa3a48e5880), 
INFO: Loaded 1 PC tables (512 PCs): 512 [0x7fa3a48d3250,0x7fa3a48d5250), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: Instrumented ru.vyarus.java.generics.resolver.util.TypeUtils (took 107 ms, size +21%)
INFO: Instrumented ru.vyarus.java.generics.resolver.util.walk.TypesVisitor (took 3 ms, size +0%)
INFO: Instrumented ru.vyarus.java.generics.resolver.util.map.IgnoreGenericsMap (took 66 ms, size +22%)
INFO: Instrumented ru.vyarus.java.generics.resolver.util.TypeUtils$1 (took 28 ms, size +15%)

DEDUP_TOKEN: c803d27b56af8836
== Java Exception: java.lang.NullPointerException: Cannot invoke "java.lang.Class.isPrimitive()" because "type" is null
	at ru.vyarus.java.generics.resolver.util.TypeUtils.wrapPrimitive(TypeUtils.java:47)
	at ru.vyarus.java.generics.resolver.GenericsResolver.resolve(GenericsResolver.java:32)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
== libFuzzer crashing input ==
MS: 0 ; base unit: 0000000000000000000000000000000000000000


artifact_prefix='./'; Test unit written to ./crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64: 
reproducer_path='.'; Java reproducer written to ./Crash_da39a3ee5e6b4b0d3255bfef95601890afd80709.java
INFO: A corpus is not provided, starting from an empty corpus
INFO: Instrumented ru.vyarus.java.generics.resolver.error.UnknownGenericException (took 97 ms, size +24%)
INFO: Instrumented ru.vyarus.java.generics.resolver.error.GenericSourceException (took 46 ms, size +11%)
INFO: Instrumented ru.vyarus.java.generics.resolver.error.GenericsException (took 17 ms, size +17%)
INFO: Instrumented ru.vyarus.java.generics.resolver.context.MethodGenericsContext (took 217 ms, size +8%)
INFO: Instrumented ru.vyarus.java.generics.resolver.context.ConstructorGenericsContext (took 104 ms, size +9%)
INFO: Instrumented ru.vyarus.java.generics.resolver.error.WrongGenericsContextException (took 76 ms, size +9%)
INFO: Instrumented ru.vyarus.java.generics.resolver.context.GenericsInfo$TypeWriter (took 3 ms, size +0%)
INFO: Instrumented ru.vyarus.java.generics.resolver.util.map.PrintableGenericsMap (took 34 ms, size +32%)
INFO: Instrumented ru.vyarus.java.generics.resolver.context.GenericsInfoFactory (took 56 ms, size +45%)

== Java Exception: java.lang.NullPointerException: Cannot read the array length because "ignoreClasses" is null
	at ru.vyarus.java.generics.resolver.context.GenericsInfoFactory.create(GenericsInfoFactory.java:47)
	at ru.vyarus.java.generics.resolver.GenericsResolver.resolve(GenericsResolver.java:34)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
== libFuzzer crashing input ==
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xa,
\012
artifact_prefix='./'; Test unit written to ./crash-adc83b19e793491b1c6ea0fd8b46cd9f32e592fc
Base64: Cg==
DEDUP_TOKEN: 79a165404bfc8505
reproducer_path='.'; Java reproducer written to ./Crash_adc83b19e793491b1c6ea0fd8b46cd9f32e592fc.java
#2	INITED cov: 8 ft: 8 corp: 1/1b exec/s: 2 rss: 2037Mb
#3	NEW    cov: 8 ft: 11 corp: 2/2b lim: 4 exec/s: 3 rss: 2037Mb L: 1/1 MS: 1 ShuffleBytes-
Unexpected exception encountered during autofuzz
com.code_intelligence.jazzer.autofuzz.AutofuzzError: 
Method: ru.vyarus.java.generics.resolver.GenericsResolver::resolve(java.lang.Class,java.lang.Class[])
this: null
Arguments: class com.code_intelligence.jazzer.autofuzz.YourAverageJavaClass, [Ljava.lang.Object;@eadd4fb
Please file an issue at:
  https://github.com/CodeIntelligenceTesting/jazzer/issues/new/choose
	at com.code_intelligence.jazzer.autofuzz.Meta.autofuzz(Meta.java:277)
	at com.code_intelligence.jazzer.autofuzz.Meta.autofuzz(Meta.java:233)
	at com.code_intelligence.jazzer.autofuzz.FuzzTarget.fuzzerTestOneInput(FuzzTarget.java:261)
	at com.code_intelligence.jazzer.autofuzz.FuzzTarget.fuzzerTestOneInput(FuzzTarget.java:226)
	at com.code_intelligence.jazzer.driver.FuzzTargetRunner.runOne(FuzzTargetRunner.java:184)
	at com.code_intelligence.jazzer.runtime.FuzzTargetRunnerNatives.startLibFuzzer(Native Method)
	at com.code_intelligence.jazzer.driver.FuzzTargetRunner.startLibFuzzer(FuzzTargetRunner.java:409)
	at com.code_intelligence.jazzer.driver.FuzzTargetRunner.startLibFuzzer(FuzzTargetRunner.java:282)
	at com.code_intelligence.jazzer.driver.Driver.start(Driver.java:88)
	at com.code_intelligence.jazzer.Jazzer.start(Jazzer.java:90)
	at com.code_intelligence.jazzer.Jazzer.main(Jazzer.java:63)
	at test.Fuzzer.main(Unknown Source)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.code_intelligence.jazzer.autofuzz.Meta.autofuzz(Meta.java:274)
	... 11 more
==67891== ERROR: libFuzzer: fuzz target exited
SUMMARY: libFuzzer: fuzz target exited
MS: 3 ChangeByte-ShuffleBytes-InsertByte-; base unit: adc83b19e793491b1c6ea0fd8b46cd9f32e592fc
0x5b,0xff,
[\377
artifact_prefix='./'; Test unit written to ./crash-8110ca510573279ffbacf62ed6d1d509b7915a87
Base64: W/8=
```

**Comment by fmeum** [comment]
Looks like the same bug as https://github.com/CodeIntelligenceTesting/jazzer/issues/582. The fix in https://github.com/CodeIntelligenceTesting/jazzer/commit/6b9a31a650441d068bbc92e4f94e7d2b85d79bcf hasn't been released on Maven yet. You can use the Docker images in the meantime.

**Comment by freedom1b2830** [comment]
0.14.0 not tested
in 0.15.0 fixed
