### ISSUE TITLE
Unable to generate Crash-hash.java

### ISSUE THREAD

**Issue by karthiv** [CodeIntelligenceTesting/jazzer#863]
The artifact for the crash is produced - however the Crash.java is not produced

Output:

```
com.code_intelligence.jazzer.api.FuzzerSecurityIssueMedium: 
at com.code_intelligence.jazzer.driver.FuzzTargetRunner.runOne(FuzzTargetRunner.java:184)
	at com.code_intelligence.jazzer.runtime.FuzzTargetRunnerNatives.startLibFuzzer(Native Method)
	at com.code_intelligence.jazzer.driver.FuzzTargetRunner.startLibFuzzer(FuzzTargetRunner.java:444)
	at com.code_intelligence.jazzer.driver.FuzzTargetRunner.startLibFuzzer(FuzzTargetRunner.java:321)
	at com.code_intelligence.jazzer.driver.Driver.start(Driver.java:145)
	at com.code_intelligence.jazzer.Jazzer.start(Jazzer.java:104)
	at com.code_intelligence.jazzer.Jazzer.main(Jazzer.java:70)

==101938== ERROR: libFuzzer: fuzz target exited
SUMMARY: libFuzzer: fuzz target exited
MS: 2 ChangeBit-Custom-; base unit: adc83b19e793491b1c6ea0fd8b46cd9f32e592fc
0x4a,
J
artifact_prefix='./'; Test unit written to ./crash-58668e7669fd564d99db5d581fcdb6a5618440b5
Base64: Sg==
```

**Comment by fmeum** [comment]
This can happen if the fuzz target exits, e.g. via `Runtime.getRuntime().halt(1)`. Since your log snippet contains a stack trace, this shouldn't have happened though.

Can you share the fuzz target that reproduces this issue? Which version of Jazzer are you using?

**Comment by karthiv** [comment]
hi,

I am using Jazzer v0.16.1

**Comment by bertschneider** [comment]
Could you please share a small fuzz target reproducing this issue, as we're not able to.

**Comment by karthiv** [comment]
Hi i resolved the issue..

**Comment by karthiv** [comment]
Hi,

I have integrated jazzer with my work.. You can refer to my work in  https://authors.elsevier.com/a/1j3039CxBmbhQ5
